// vue/src/components/TodoItem.vue
<template>
  <li>
    <button
      class="btn btn-danger"
      v-if="editable"
      @click="$emit('removeTodo', todo)"
    >
      X
    </button>
    <button
      class="btn btn-warning"
      v-if="editable"
      @click="$emit('editTodo', todo)"
    >Edit</button>
    <span class="todo-text">{{ todo.msg }}</span>
    <button
      class="btn btn-success"
      v-if="editable"
      @click="$emit('doneTodo', todo)"
    >OK</button>
  </li>
</template>

<script>
export default {
  props: {
    todo: { type: Object },
    editable: { type: Boolean, default: false }
  }
}
</script>

<style scoped>
li {
  list-style: none;
  padding: 2px 0;
}

span.todo-text {
  padding: 0 8px;
}
</style>

// react/src/components/todoItem/todoItem.js
import React, { Component } from "react";

class TodoItem extends Component {
  removeTodo = () => {
    this.props.removeTodo(this.props.todo);
  };

  editTodo = () => {
    this.props.editTodo(this.props.todo);
  };

  doneTodo = () => {
    this.props.doneTodo(this.props.todo);
  };

  render() {
    if (this.props.editable) {
      return (
        <li>
          <button className="btn btn-danger" onClick={this.removeTodo}>
            X
          </button>
          <button className="btn btn-warning" onClick={this.editTodo}>
            Edit
          </button>
          <span className="todo-text">{this.props.todo.msg}</span>
          <button className="btn btn-success" onClick={this.doneTodo}>
            OK
          </button>
        </li>
      );
    } else {
      return (
        <li>
          <span className="todo-text">{this.props.todo.msg}</span>
        </li>
      );
    }
  }
}

export default TodoItem;
