// react/src/views/concluidos/concluidos.js
import React, { Component } from "react";
import Header from "../../components/header/header";
import TodoItem from "../../components/todoItem/todoItem";

class Concluidos extends Component {
  constructor(props) {
    super(props);

    this.state = {
      todos: JSON.parse(localStorage.getItem("listaTodosDone")) || []
    };
  }

  clearDoneTodos = () => {
    this.setState({
      todos: []
    });
    localStorage.setItem("listaTodosDone", JSON.stringify(this.state.todos));
  };

  render() {
    return (
      <div className="center-flex">
        <Header />
        <div className="todos center-flex">
          <h1>
            Tarefas Concluídas
            <button
              className="btn btn-outline-danger"
              onClick={this.clearDoneTodos}
            >
              Limpar
            </button>
          </h1>
          <ul className="item-done">
            {this.state.todos.map((todo, idx) => {
              return <TodoItem key={idx} todo={todo} />;
            })}
          </ul>
        </div>
      </div>
    );
  }
}

export default Concluidos;

// vue/src/views/Concluidos.vue
<template>
  <div class="todos center-flex">
    <h1>
      Tarefas Concluídas
      <button
        class="btn btn-outline-danger"
        @click="clearDoneTodos"
      >Limpar</button>
    </h1>
    <ul>
      <todo-item
        class="item-done"
        v-for="(todo, index) in todos"
        :key="index"
        :todo="todo"
      />
    </ul>
  </div>
</template>

<script>
import TodoItem from '@/components/TodoItem'

export default {
  components: {
    TodoItem
  },
  data () {
    return {
      todos: []
    }
  },
  methods: {
    clearDoneTodos () {
      this.todos = []
      localStorage.setItem('listaTodosDone', JSON.stringify(this.todos))
    }
  },
  mounted () {
    this.todos = JSON.parse(localStorage.getItem('listaTodosDone')) || []
  }
}
</script>

<style scoped>
.todos {
  padding-top: 100px;
}

.item-done {
  text-decoration: line-through;
}
</style>
