// vue/src/views/Todos.vue
<template>
  <div class="todos center-flex">
    <h1>Lista de Tarefas</h1>
    <new-todo @newTodo="addTodo" />
    <ul>
      <todo-item
        v-for="(todo, index) in todos"
        :key="index"
        :todo="todo"
        @removeTodo="removeTodo"
        @editTodo="editTodo"
        @doneTodo="doneTodo"
        editable
      />
    </ul>
  </div>
</template>

<script>
import NewTodo from '@/components/NewTodo.vue'
import TodoItem from '@/components/TodoItem.vue'

export default {
  components: {
    NewTodo,
    TodoItem
  },
  data () {
    return {
      todos: []
    }
  },
  methods: {
    addTodo (newtodo) {
      this.todos.unshift(newtodo)
      localStorage.setItem('listaTodos', JSON.stringify(this.todos))
    },
    removeTodo (todo) {
      this.todos.splice(this.todos.indexOf(todo), 1)
      localStorage.setItem('listaTodos', JSON.stringify(this.todos))
    },
    editTodo (todo) {
      const newTodo = { msg: prompt('Informe o novo texto do item:', todo.msg) }
      this.todos.splice(this.todos.indexOf(todo), 1, newTodo)
    },
    doneTodo (todo) {
      const doneTodos = JSON.parse(localStorage.getItem('listaTodosDone')) || []
      this.todos.splice(this.todos.indexOf(todo), 1)
      localStorage.setItem('listaTodos', JSON.stringify(this.todos))

      doneTodos.push(todo)
      localStorage.setItem('listaTodosDone', JSON.stringify(doneTodos))
    }
  },
  mounted () {
    this.todos = JSON.parse(localStorage.getItem('listaTodos')) || []
  }
}
</script>

<style scoped>
.todos {
  padding-top: 100px;
}
</style>

// react/src/views/todos/todos.js
import React, { Component } from "react";
import Header from "../../components/header/header";
import TodoItem from "../../components/todoItem/todoItem";
import NewTodo from "../../components/newTodo/newTodo";

class Todos extends Component {
  constructor(props) {
    super(props);

    this.state = {
      todos: JSON.parse(localStorage.getItem("listaTodos")) || []
    };
  }

  removeTodo = todo => {
    const todoList = this.state.todos;
    todoList.splice(todoList.indexOf(todo), 1);
    this.setState({
      todos: todoList
    });
    localStorage.setItem("listaTodos", JSON.stringify(todoList));
  };

  editTodo = todo => {
    const todoList = this.state.todos;
    const newTodo = {
      msg: prompt("Informe o novo texto do item:", todo.msg)
    };
    todoList.splice(todoList.indexOf(todo), 1, newTodo);
    this.setState({
      todos: todoList
    });
    localStorage.setItem("listaTodos", JSON.stringify(todoList));
  };

  doneTodo = todo => {
    const todoList = this.state.todos;
    const doneTodos = JSON.parse(localStorage.getItem("listaTodosDone")) || [];
    todoList.splice(todoList.indexOf(todo), 1);

    this.setState({
      todos: todoList
    });
    localStorage.setItem("listaTodos", JSON.stringify(todoList));

    doneTodos.push(todo);
    localStorage.setItem("listaTodosDone", JSON.stringify(doneTodos));
  };

  newTodo = newTodo => {
    const todoList = this.state.todos;
    todoList.unshift(newTodo);
    this.setState({
      todos: todoList
    });
    localStorage.setItem("listaTodos", JSON.stringify(todoList));
  };

  render() {
    return (
      <div className="center-flex">
        <Header />
        <div className="todos center-flex">
          <h1> Lista de Tarefas </h1> <NewTodo newTodo={this.newTodo} />
          <ul>
            {this.state.todos.map((todo, idx) => {
              return (
                <TodoItem
                  key={idx}
                  todo={todo}
                  doneTodo={this.doneTodo}
                  editTodo={this.editTodo}
                  removeTodo={this.removeTodo}
                  editable
                />
              );
            })}
          </ul>
        </div>
      </div>
    );
  }
}

export default Todos;
